name: Build and deploy fullstack app to Azure Web App - DocuGen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------
      # Backend Setup
      # --------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      # --------------------
      # Frontend Setup
      # --------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm ci
          npm run build

      # --------------------
      # Copy frontend build to backend
      # --------------------
      - name: Copy frontend build to backend
        run: |
          mkdir -p backend/frontend/build
          cp -r frontend/build/* backend/frontend/build/

      # --------------------
      # Upload artifact for deploy
      # --------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: |
            backend
            !backend/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DocuGen' # 🔥 replace with your Web App name
          slot-name: 'Production'
          package: backend
          startup-command: 'gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app'
